[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "htmdec_models"
version = "0.1.0"
description = "Deployer of GEMD data models pertaining to HTMDEC"
readme = "README.md"
authors = ["Ali Rachidi <arachid1@jhu.edu>"]
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
packages = [{ include = "*", from = "src" }] 

[tool.poetry.dependencies]
python = ">=3.9,<3.11"  
openmsimodel = "0.2.0.dev1"
numpy = "1.21"
watchdog = "*"
girder_client = "*"

[tool.poetry.dev-dependencies]
pytest = "^7.0"


